using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Moq;
using TestClasses;

namespace TestClasses.Tests
{
    [TestFixture]
    public class Class2Tests
    {
        private Class2 Class2Obj;
        [OneTimeSetUp]
        public void SetUp()
        {
            Class2Obj = new Class2();
        }

        [Test]
        public void Method_1Test()
        {
            Class2Obj.Method();
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Method_2Test()
        {
            int x = default;
            Class2Obj.Method(x);
            Assert.Fail("autogenerated");
        }
    }
}