using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Moq;
using TestClasses;

namespace TestClasses.Tests
{
    [TestFixture]
    public class Class1Tests
    {
        private Class1 Class1Obj;
        [OneTimeSetUp]
        public void SetUp()
        {
            Class1Obj = new Class1();
        }

        [Test]
        public void Method1Test()
        {
            Class1Obj.Method1();
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Method2Test()
        {
            int actual = Class1Obj.Method2();
            int expected = default;
            Assert.AreEqual(actual, expected);
            Assert.Fail("autogenerated");
        }
    }
}