using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Moq;
using TestClasses;

namespace TestClasses.Tests
{
    [TestFixture]
    public class Class4Tests
    {
        private Mock<IInterface> _interface;
        private string s;
        private int i;
        private Class4 Class4Obj;
        [OneTimeSetUp]
        public void SetUp()
        {
            _interface = new Mock<IInterface>();
            s = default;
            i = default;
            Class4Obj = new Class4(_interface.Object, s, i);
        }

        [Test]
        public void MethodTest()
        {
            int i = default;
            int actual = Class4Obj.Method(i);
            int expected = default;
            Assert.AreEqual(actual, expected);
            Assert.Fail("autogenerated");
        }
    }
}