using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using TestClasses;

namespace TestClasses.Tests
{
    [TestFixture]
    public class Class2Tests
    {
        [Test]
        public void Method_1Test()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Method_2Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}